repos:
  # Default checks
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: check-ast
  - id: check-yaml
  - id: check-json
  - id: check-toml
  - id: check-merge-conflict
  - id: no-commit-to-branch
  - id: pretty-format-json

  # Python linter
- repo: https://github.com/psf/black
  rev: 23.10.0
  hooks:
  - id: black

  # Poetry stuff
- repo: https://github.com/python-poetry/poetry
  rev: 1.6.1
  hooks:
  - id: poetry-check
  # - id: poetry-lock # This updates packages, we might want it in the future
