# Colors
theme_color: "#0395DE" # Cool blue
sidebar_color: "#F6F6F6" # Light grey
bar_background_color: "#DFDFDF" # Darker light grey
date2_color: "#616161" # Grey

# Sizes
padding: 12
page_width: 210
page_height: 297
sidebar_width: 60
h2_padding_left: 4
date_container_width: 13
date_container_padding_left: 8
description_container_padding_left: 3

# Frame for previewing
frame_padding: 10 # For preview in html
frame_color: "#BDBDBD"
